### ISSUE TITLE
reportMilestone

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#15]
This concept is currently being used out in the wild when what should be used instead is the standard existing term progressReportNumber. 

Recommendation: replace instances of non-compliant term with progressReportNumber

**Comment by allaway** [comment]
## Curation Review — NADIA Agent

**Synapse Project:** [syn74276737](https://www.synapse.org/#!Synapse:syn74276737)
**Source:** Zenodo:14248993
**PMID:** [39847441](https://pubmed.ncbi.nlm.nih.gov/39847441/)
**DOI:** 10.1093/neuonc/noaf016

### Changes Applied

**Publication:** *Spatially resolved transcriptomics of benign and malignant peripheral nerve sheath tumors* (Neuro-Oncology 2025)
**Authors:** Juliane Bremer (first), Dieter Henrik Heiland (last/PI) — Freiburg/Aachen

**Annotation corrections:**
-  → corrected to ,  (ForeName LastName; previous had , )
-  → reformatted to fit 500-character annotation limit
-  → kept , ,  (correct; study spans all NF1-associated PNST types)
-  → removed from 2 File entities

**File-level annotations set:**
- :  (Zenodo contains spatial transcriptomic data; confirmed by paper title)
- :  (human PNST tumor tissue)
- : 
- : 
- : 
- :  (AnnData format typical for spatial transcriptomic Zenodo deposits)
- : 

**Note:** Only 2 files in the Raw Data folder — this Zenodo deposit likely contains processed count matrices or AnnData objects rather than raw FASTQ files.

**Files updated:** 2
