### ISSUE TITLE
Remove biothings import from JSON-LD

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#194]
This avoids potential conflicts/hidden issues and keeps schema cleaner.

More hacky way to do it: https://github.com/Sage-Bionetworks/schematic/issues/708#issuecomment-1191541035

Official way (wip to expose CLI param): https://github.com/Sage-Bionetworks/schematic/issues/856

**Comment by allaway** [comment]
## Curation Review — NADIA Agent

**Synapse Project:** [syn74319558](https://www.synapse.org/#!Synapse:syn74319558)
**Source:** Zenodo:10.5281/zenodo.17312999
**PMID:** Not found

### Changes Applied

**Study:** Transcriptomic data and analysis code for a study on oxidative stress in vestibular schwannoma.

**Annotation corrections:**
- `diseaseFocus` → corrected to `Neurofibromatosis type 2`, `Schwannomatosis` (vestibular schwannoma is NF2/SMARCB1-related, not NF1)
- `manifestation` → kept `Schwannoma`, `Vestibular Schwannoma` (correct)
- `studyLeads` → corrected to `Yubin Xue`, `Mingyue Wang` (ForeName LastName order, not reversed)
- `doi` → confirmed `10.5281/zenodo.17312999`
- `fundingAgency` → `Not Applicable (External Study)` (no grants found in Zenodo record)

**Note:** This Zenodo deposit appears to be newly uploaded (record ID 17312999 is very high, suggesting 2025). 0 file entities found inside the Raw Data folder — the data files may be linked externally via Zenodo URLs rather than uploaded to Synapse. Data manager should verify file linkage.

**Files updated:** 0
