### ISSUE TITLE
Add Cherry Imaging to platform

### ISSUE THREAD

**Issue by allaway** [nf-osi/nf-metadata-dictionary#269]
**List the new value**
Value: `Cherry Imaging system`

**Provide definition and source for the new value**
Definition: A three-dimensional imaging system from Cherry Imaging
Source url: https://pubmed.ncbi.nlm.nih.gov/34773721/

**Are there similar but not-quite-right values?**
Please list if applicable.

**Additional comments**

**Comment by allaway** [comment]
Relevant to https://github.com/nf-osi/dcc-site/pull/384/

**Comment by anngvu** [comment]
@allaway Just making sure that you want a more generic "Cherry Imaging system" instead of the more specific terms added here awhile ago: 
- [Cherry Imaging TRACE Platform](https://github.com/nf-osi/nf-metadata-dictionary/blob/main/NF.jsonld#L5916)
- [Cherry Imaging FACE Platform](https://github.com/nf-osi/nf-metadata-dictionary/blob/main/NF.jsonld#L5933)

**Comment by allaway** [comment]
I missed those, thanks!
