### ISSUE TITLE
Make annotations required for RNA sequencing 

### ISSUE THREAD

**Issue by cconrad8** [nf-osi/nf-metadata-dictionary#277]
Change the following annotations to be required for RNA sequencing: 

https://github.com/nf-osi/nf-metadata-dictionary/blob/e7268f2ef696c60b75a121f20790473d2ec464c8/docs/templates/RNASeq_Template.csv

individualID
specimenID 
assay 
species
libraryPreparationMethod
Platform
readPair
specimenPreparationMethod
tumorType

This would help us eliminate the need to ask people afterwards for the annotations. It would allow users to re-process the data including us for NTAP projects.  

Potentially also do for WES and WGS

**Comment by allaway** [comment]
I agree with this. However, I have a thought about readPair - this one might not apply in all cases. For example, if the data are in BAM or CRAM format, this is not applicable. I don't think we should add "not applicable" as a value, because it adds unnecessary annotation burden rather than just leaving it blank. Also, this one is almost always possible to infer from the name (e.g. the filename usually ends in _R1 or _1,  _R2 or _2), so we can add those annotations without reaching out to the PI.

**Comment by cconrad8** [comment]
@allaway agree with you on "read pair" not being included.  Thanks!

**Comment by anngvu** [comment]
Notes:
- `assay` and `platform` already required, e.g. https://github.com/nf-osi/nf-metadata-dictionary/blob/main/NF.jsonld#L4810
- not requiring `readPair`
